### PR TITLE
add laravel 7 support

### PR DESCRIPTION
**Pull request by bomshteyn**

### CODE REVIEW

**Comment by SUKOHI** [comment]
Hi, bomshteyn.
Thank you for your contribution!

**Comment by hugoleon46** [comment]
Hey @SUKOHI .

I'm upgrading my project to Laravel 7, and I saw this message when using Composer update command:

`sukohi/fluent-csv 3.0.0 requires illuminate/support ^5.7|^6.0`

I saw that this was already solved with the latest pull request. Maybe it only takes creating a new release for Composer to take these changes. I wanted to create the release or tag at least as if it were another pull request, but unfortunately I'm not quite sure how it works.

Could you please create a new release so that it is possible to use this last change in Composer?.

Thank you very much in advance!.

**Comment by SUKOHI** [comment]
Hi, @hugoleon46.
Thank you for your message!

Sorry, the latest version didn't support 7.x as you mentioned.
I added new release as 3.0.4.
Could you please try it again?

**Comment by hugoleon46** [comment]
Hey @SUKOHI.

I just had the library installed again and the above message no longer came out. I also did some tests and it is working correctly just like before.

Many thanks!.

**Pull request merged**
